### ISSUE TITLE
Add Multiple Strokes to the novel GEGL Stroke filter. (Help Needed)

### ISSUE THREAD

**Issue by LinuxBeaver** [LinuxBeaver/GEGL_Stroke#1]
In the GEGL Graph it is possible to make many strokes. I want the GUI to be able to make at least two or three of them but I do not know how to do this.

![image](https://user-images.githubusercontent.com/78667207/167303818-032b19cf-5ea9-433f-94b9-ebc841d74da6.png)

![image](https://user-images.githubusercontent.com/78667207/167303884-daebf41e-d132-49e1-ae53-4bc0a126b804.png)

**Comment by LinuxBeaver** [comment]
Multistroke is making progress.
https://github.com/LinuxBeaver/GEGL_Stroke/tree/MultiStroke-(incomplete)

The dialogs are there and they work but they both control the same stroke. I don't know how to make two of them

![image](https://user-images.githubusercontent.com/78667207/167324144-2933424f-3962-488d-af29-a39bd9e65f27.png)

**Comment by LinuxBeaver** [comment]
![image](https://user-images.githubusercontent.com/78667207/167344508-9b4855e0-25bb-4154-aa46-5d306f0f661c.png)
![image](https://user-images.githubusercontent.com/78667207/167344515-f47a6f75-42f6-4254-8a46-07af89191ecb.png)

**Comment by PatLabGit** [comment]
If I may suggest, on the UI you might want to show only the setting for 1 stroke, than have a "+" or "More" button to add a second stroke with its setting, and so, instead of giving a "forced / mandatory" 3 strokes.
Just my 2 cents ;)
